//! The npm backend for pmpx.
//!
//! Pure mapping: a verb plus its arguments in, one command out. It reads nothing, writes
//! nothing, and never looks at the environment -- everything the plugin is allowed to know
//! arrives in [`Context`], which the host filled in from files it already stat'd.

use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

struct Npm;

impl PackageManager for Npm {
    fn name(&self) -> &str {
        "npm"
    }

    fn family(&self) -> Family {
        Family::NODE
    }

    fn command(
        &self,
        _ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        let spec = match verb {
            // No argument at all is a plain `npm install`: npm resolves everything from
            // package.json and the lockfile by itself, so no flag is needed to say so.
            Verb::Install if args.is_empty() => CommandSpec::new("npm").arg("install"),
            // With package names the same subcommand adds them: npm spells "add" as
            // `npm install <pkg>...`, unlike cargo's separate `add`.
            Verb::Install => CommandSpec::new("npm").arg("install").args(args.iter()),

            // npm's counterpart of "remove" is `uninstall`.
            Verb::Remove => CommandSpec::new("npm").arg("uninstall").args(args.iter()),

            // The args are `[script, ...passed to the script]`, flattened by the host, so the
            // first one is the script name and belongs right after `run`. `--` goes between the
            // script name and the rest: npm treats the elements before it as its own options, and
            // `npm run dev --port 3000` makes npm read `--port` as configuration of its own
            // instead of passing it on.
            Verb::Run => match args.split_first() {
                None => CommandSpec::new("npm").arg("run"),
                Some((script, rest)) => {
                    let mut spec = CommandSpec::new("npm").arg("run").arg(script);
                    if !rest.is_empty() {
                        spec = spec.arg("--").args(rest.iter());
                    }
                    spec
                }
            },

            // `pmpx build` means the project's own build script, so the verb expands to
            // `npm run build` rather than to a subcommand npm does not have.
            Verb::Build => run_script("build", args),

            // `test` is one of npm's built-in aliases, so it is written the way npm documents it
            // -- `npm test`, not `npm run test` -- and the `--` is inserted the same way `run`
            // does it.
            Verb::Test if args.is_empty() => CommandSpec::new("npm").arg("test"),
            Verb::Test => CommandSpec::new("npm")
                .arg("test")
                .arg("--")
                .args(args.iter()),

            // `npm update` takes package names as positional arguments, so no flag is needed.
            Verb::Update if args.is_empty() => CommandSpec::new("npm").arg("update"),
            Verb::Update => CommandSpec::new("npm").arg("update").args(args.iter()),

            // npx ships with npm, so the escape hatch is the same executable, not a second tool.
            Verb::Exec => CommandSpec::new("npx").args(args.iter()),
        };

        Ok(spec)
    }
}

/// `npm run <name>` with `args` forwarded to the script.
///
/// npm is the one backend that has to insert the `--` itself, and the other three do not. This
/// is measured, not assumed:
///
/// ```text
/// $ npm run probe --foo
/// npm warn Unknown cli config "--foo". This will stop working in the next major version of npm.
///                                    <- npm swallowed --foo as its own configuration and the
///                                       script never saw it
///
/// $ npm run probe -- --foo
/// GOT:--foo                          <- with the `--` it arrives
/// ```
///
/// pnpm, yarn and bun behave the other way round: there the `--` is passed through to the script
/// verbatim, so those backends must not insert one. That is why this lives here and in no shared
/// helper.
///
/// `--` is omitted when there is nothing to forward: npm accepts a bare trailing one, but then
/// the script receives a `--` argument of its own. `Verb::Test` does not go through here because
/// npm writes that one as `npm test`, without `run`.
fn run_script(name: &str, args: &[OsString]) -> CommandSpec {
    let mut spec = CommandSpec::new("npm").arg("run").arg(name);
    if !args.is_empty() {
        spec = spec.arg("--").args(args.iter());
    }
    spec
}

/// The factory that the wrapper crate generated by crate-plugin-kit calls.
pub fn create() -> Box<dyn PackageManager> {
    Box::new(Npm)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn ctx() -> Context {
        Context {
            project_root: PathBuf::from("/tmp/proj"),
            matched: vec!["package-lock.json".to_string(), "package.json".to_string()],
        }
    }

    /// The exact argv the backend gets spawned with, program first.
    fn argv(verb: Verb, args: &[&str]) -> Vec<String> {
        let args: Vec<OsString> = args.iter().map(OsString::from).collect();
        let spec = Npm.command(&ctx(), verb, &args).expect("should map");
        std::iter::once(spec.program.to_string_lossy().into_owned())
            .chain(spec.args.iter().map(|a| a.to_string_lossy().into_owned()))
            .collect()
    }

    #[test]
    fn name_and_family_match_the_manifest() {
        assert_eq!(Npm.name(), "npm");
        assert_eq!(Npm.family(), Family::NODE);
    }

    #[test]
    fn install_without_arguments_installs_the_lockfile() {
        assert_eq!(argv(Verb::Install, &[]), ["npm", "install"]);
    }

    #[test]
    fn install_with_arguments_adds_packages() {
        assert_eq!(
            argv(Verb::Install, &["left-pad", "typescript"]),
            ["npm", "install", "left-pad", "typescript"]
        );
    }

    #[test]
    fn remove_uninstalls_packages() {
        assert_eq!(
            argv(Verb::Remove, &["left-pad"]),
            ["npm", "uninstall", "left-pad"]
        );
    }

    /// The first argument is the script name and goes directly after `run`; everything after it
    /// is forwarded to the script, behind the `--` that npm requires.
    #[test]
    fn run_takes_the_script_name_then_forwards_arguments_after_a_double_dash() {
        // `pmpx run probe --foo` -> `npm run probe -- --foo`
        assert_eq!(
            argv(Verb::Run, &["probe", "--foo"]),
            ["npm", "run", "probe", "--", "--foo"]
        );
        assert_eq!(
            argv(Verb::Run, &["dev", "--port", "3000"]),
            ["npm", "run", "dev", "--", "--port", "3000"]
        );
        // A script name on its own has nothing to forward, so no `--` is appended.
        assert_eq!(argv(Verb::Run, &["dev"]), ["npm", "run", "dev"]);
        assert_eq!(argv(Verb::Run, &[]), ["npm", "run"]);
    }

    #[test]
    fn build_runs_the_build_script() {
        assert_eq!(argv(Verb::Build, &[]), ["npm", "run", "build"]);
        assert_eq!(
            argv(Verb::Build, &["--watch"]),
            ["npm", "run", "build", "--", "--watch"]
        );
    }

    /// The `--` is inserted and never inspected, so one that pmpx already wrote passes through as
    /// a plain argument. `pmpx test -- --runInBand` reaches the plugin as `["--", "--runInBand"]`
    /// and becomes argv `["npm", "test", "--", "--", "--runInBand"]`, which is npm's
    /// `npm test -- -- --runInBand`.
    #[test]
    fn test_runs_the_test_script() {
        assert_eq!(argv(Verb::Test, &[]), ["npm", "test"]);
        assert_eq!(
            argv(Verb::Test, &["--watch"]),
            ["npm", "test", "--", "--watch"]
        );
        assert_eq!(
            argv(Verb::Test, &["--", "--runInBand"]),
            ["npm", "test", "--", "--", "--runInBand"]
        );
    }

    #[test]
    fn update_takes_package_names_positionally() {
        assert_eq!(argv(Verb::Update, &[]), ["npm", "update"]);
        assert_eq!(
            argv(Verb::Update, &["typescript"]),
            ["npm", "update", "typescript"]
        );
    }

    #[test]
    fn exec_goes_through_npx() {
        assert_eq!(argv(Verb::Exec, &["cowsay", "hi"]), ["npx", "cowsay", "hi"]);
        assert_eq!(argv(Verb::Exec, &[]), ["npx"]);
    }
}
